-- Spring Modulith Event Publication Registry v3 schema
-- Supports at-least-once delivery with transactional outbox pattern
-- Managed via Flyway (auto-init disabled in config)

CREATE TABLE IF NOT EXISTS EVENT_PUBLICATION (
    ID                     VARCHAR(36)   NOT NULL,
    LISTENER_ID            VARCHAR(512)  NOT NULL,
    EVENT_TYPE             VARCHAR(512)  NOT NULL,
    SERIALIZED_EVENT       TEXT          NOT NULL,
    PUBLICATION_DATE       TIMESTAMP(6)  NOT NULL,
    COMPLETION_DATE        TIMESTAMP(6)  NULL DEFAULT NULL,
    STATUS                 VARCHAR(20)   NULL DEFAULT NULL,
    COMPLETION_ATTEMPTS    INT           NULL DEFAULT NULL,
    LAST_RESUBMISSION_DATE TIMESTAMP(6)  NULL DEFAULT NULL,
    PRIMARY KEY (ID),
    INDEX EVENT_PUBLICATION_BY_COMPLETION_DATE_IDX (COMPLETION_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Spring Modulith 事件发布注册表';

CREATE TABLE IF NOT EXISTS EVENT_PUBLICATION_ARCHIVE (
    ID                     VARCHAR(36)   NOT NULL,
    LISTENER_ID            VARCHAR(512)  NOT NULL,
    EVENT_TYPE             VARCHAR(512)  NOT NULL,
    SERIALIZED_EVENT       TEXT          NOT NULL,
    PUBLICATION_DATE       TIMESTAMP(6)  NOT NULL,
    COMPLETION_DATE        TIMESTAMP(6)  NULL DEFAULT NULL,
    STATUS                 VARCHAR(20)   NULL DEFAULT NULL,
    COMPLETION_ATTEMPTS    INT           NULL DEFAULT NULL,
    LAST_RESUBMISSION_DATE TIMESTAMP(6)  NULL DEFAULT NULL,
    PRIMARY KEY (ID),
    INDEX EVENT_PUBLICATION_ARCHIVE_BY_COMPLETION_DATE_IDX (COMPLETION_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Spring Modulith 事件发布归档表';
