apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mysql.yaml
  - redis.yaml
  - rabbitmq.yaml
  - services.yaml
secretGenerator:
  - name: easyorange-infra-secrets
    envs:
      - env/infra.env
